ManejoPresupuestoApp/Controllers/CuentasController.cs
using ManejoPresupuestoApp.Models;
using ManejoPresupuestoApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using AutoMapper;

namespace ManejoPresupuestoApp.Controllers
{
    public class CuentasController : Controller
    {
        private readonly IRepositoriosTiposCuentas _repositoriosTiposCuentas;
        private readonly IRepositoriosCuentas _repositoriosCuentas;
        private readonly IRepositoriosTransacciones _repositoriosTransacciones;
        private readonly IServiciosUsuarios _serviciosUsuarios;
        private readonly IServiciosReporte _serviciosReporte;

        private readonly IMapper _mapper;

        public CuentasController (IRepositoriosTiposCuentas repositoriosTiposCuentas,
                                    IRepositoriosCuentas repositoriosCuentas,
                                    IServiciosUsuarios serviciosUsuarios,
                                    IRepositoriosTransacciones repositoriosTransacciones,
                                    IServiciosReporte serviciosReporte,
                                    IMapper mapper)
        {
            _repositoriosTiposCuentas = repositoriosTiposCuentas;
            _repositoriosCuentas = repositoriosCuentas;
            _serviciosUsuarios = serviciosUsuarios;
            _repositoriosTransacciones = repositoriosTransacciones;
            _mapper = mapper;
            _serviciosReporte = serviciosReporte;
        }


        public async Task<IActionResult> Index()
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            var lstCuentas = await _repositoriosCuentas.ListadoCuentas(usuarioId);

            var modelo = lstCuentas.GroupBy(x => x.TipoCuenta).Select(x => new IndiceCuentaModel
            {
                TipoCuenta = x.Key,
                Cuentas = x.AsEnumerable()
            });         

            return View(modelo);
        }

        public async Task<IActionResult> Crear()
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            CuentaViewModel cuenta = new CuentaViewModel();
            var tipoCuenta = await _repositoriosTiposCuentas.ConsultarPorId(cuenta.TipoCuentaId, usuarioId);
            if (tipoCuenta == null)
                RedirectToAction("NoEncontrado", "Home");

            cuenta.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
            return View(cuenta);
        }

        [HttpPost]
        public async Task<IActionResult> Crear(CuentaViewModel cuenta)
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await _repositoriosTiposCuentas.ConsultarPorId(cuenta.TipoCuentaId, usuarioId);
            if (tipoCuenta == null)
                RedirectToAction("NoEncontrado","Home");

            if (!ModelState.IsValid)
            {
                cuenta.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
                return View(cuenta);
            }

            await _repositoriosCuentas.Crear(cuenta);
            return RedirectToAction("Index");
        }

        public async Task<IEnumerable<SelectListItem>> ObtenerTiposCuentas(int usuarioId)
        {
            var tiposCuentas = await _repositoriosTiposCuentas.ListadoTiposCuentas(usuarioId);            
            return tiposCuentas.Select(x => new SelectListItem(x.Nombre, x.Id.ToString()));
        }


        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            Cuenta cuenta = await _repositoriosCuentas.ConsultarPorId(id, usuarioId);
            if (cuenta == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            var tiposCuentas = await ObtenerTiposCuentas(usuarioId);
            var cuentaModel = _mapper.Map<CuentaViewModel>(cuenta);
            cuentaModel.TiposCuentas = tiposCuentas;

            return View(cuentaModel);
        }

        [HttpPost]
        public async Task<IActionResult> Modificar(CuentaViewModel cuenta)
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await _repositoriosTiposCuentas.ConsultarPorId(cuenta.TipoCuentaId, usuarioId);
            if (tipoCuenta == null)

                RedirectToAction("NoEncontrado", "Home");

            if (!ModelState.IsValid)
            {
                cuenta.TiposCuentas = await ObtenerTiposCuentas(usuarioId);
                return View(cuenta);
            }

            await _repositoriosCuentas.Modificar(cuenta);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Borrar(int id)
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            var cuenta = await _repositoriosCuentas.ConsultarPorId(id, usuarioId);
            if (cuenta == null)
                return RedirectToAction("NoEncontrado", "Home");

            return View(cuenta);
        }

        [HttpPost]
        public async Task<IActionResult> BorrarCuenta(int id)
        {
            try
            {
                int resultado = await _repositoriosCuentas.Borrar(id);
                if (resultado == 0)
                    throw new Exception("No hay datos a borrar");
            }
            catch (Exception ex)
            {
                //Se añade error al modelo
                ModelState.AddModelError(string.Empty, ex.Message);
                return View("Index");
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detalle(int id, int mes, int año)
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            var cuenta = await _repositoriosCuentas.ConsultarPorId(id, usuarioId);
            if (cuenta == null)
                return RedirectToAction("NoEncontrado", "Home");

            var modelo = await _serviciosReporte.ObtenerTransaccionesDetalladasPorCuenta(usuarioId, id, mes, año, ViewBag);
            ViewBag.Cuenta = cuenta.Nombre;

            return View(modelo);
        }

    }
}

ManejoPresupuestoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManejoPresupuestoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ManejoPresupuestoApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.1/main.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Transacciones" asp-action="Index">ManejoPresupuestoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacciones" asp-action="Index">Transacciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TiposCuentas" asp-action="Index">Tipos Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuentas" asp-action="Index">Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                    </ul>
                    <div class="ms-auto">
                        <select class="form-control" id="langSelect">
                            <option default>Idioma</option>
                            <option value="ES">Español</option>
                            <option value="EN">Ingles</option>
                        </select>
                    </div>
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ManejoPresupuestoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javascript">
       $(function () {
            const urlParams = new URLSearchParams(window.location.search);
            const culture = urlParams.get('culture') ?? "";
            
            if (culture != "") {
                 if (culture == "en-US") {
                    $("#langSelect").val("EN");
                 } else {
                    $("#langSelect").val("ES");
                 }
            }
       
            $("#langSelect").change(function () {
               var redirect = 
                    $("#langSelect").val() == "EN" ? 
                    "?culture=en-US" : "?culture=es-ES";
                    window.location.href = redirect;
            });
       })
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ManejoPresupuestoApp/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> SignInManager

<ul class="navbar-nav" style="margin-left:5em">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="Logout" asp-controller="usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">LogOut</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-action="Registro" asp-controller="usuarios">
                Registro
             </a>
        </li>
         <li class="navbar-item">
            <a class="nav-link text-dark" asp-action="Login" asp-controller="usuarios">
                Login
             </a>
        </li>
    }
</ul>

ManejoPresupuestoApp/Views/Shared/_NavegarMeses.cshtml
@model DateTime
<h4>
    <a asp-route-mes="@ViewBag.MesAnterior" asp-route-año="@ViewBag.AñoAnterior"
    class="btn-secondary btn"
    ><i class="bi-chevron-left"></i></a>
    @Model.ToString("MMMM")-@Model.Year
    <a asp-route-mes="@ViewBag.MesPosterior" asp-route-año="@ViewBag.AñoPosterior"
    class="btn-secondary btn"
    ><i class="bi-chevron-right"></i></a>
</h4>

ManejoPresupuestoApp/Views/Shared/_ReporteTransaccionesDetalladas.cshtml
@model TransaccionesDetalladas

@{
    TransaccionesResumenTotal resumenTotal = new TransaccionesResumenTotal()
    {
        Ingresos = Model.BalanceDepositos,
        Gastos = Model.BalanceGastos,
        Total = Model.Total
    };
}

<partial name="_ResumenTotales" model="resumenTotal" />

@if (Model.TransaccionesAgrupadas.Count() == 0)
{
    <h5>No hay datos para mostrar</h5>
}
else
{
    <table class="table">
        <tbody>
            @foreach (var grupoTransaccion in Model.TransaccionesAgrupadas)
            {
                <tr class="colorFila">
                    <td colspan=3>@grupoTransaccion.FechaTransaccion.Day
                        <span class="badge bg-secondary">
                            @grupoTransaccion.FechaTransaccion.ToString("ddd")
                        </span>
                    </td>
                    <td class="activo">@(grupoTransaccion.BalanceDepositos > 0 ? grupoTransaccion.BalanceDepositos.ToString("N"): null)</td>
                    <td class="pasivo">@(grupoTransaccion.BalanceGastos > 0 ? grupoTransaccion.BalanceGastos.ToString("N"): null)</td>
                </tr>
                @foreach (var transaccion in grupoTransaccion.Transacciones)
                {
                    <tr>
                        <td>
                            <a asp-controller="transacciones" asp-action="modificar" 
                            asp-route-id="@transaccion.Id" asp-route-urlRetorno="@ViewBag.urlRetorno">
                                <i class="bi-pencil"></i>
                            </a>
                        </td>
                        <td>@transaccion.Categoria</td>
                        <td>@transaccion.Cuenta</td>
                        <td class="activo">@(transaccion.TipoOperacionId==TipoOperacion.Ingreso ? transaccion.Monto.ToString("N") : null)</td>
                        <td class="pasivo">@(transaccion.TipoOperacionId==TipoOperacion.Gasto ? transaccion.Monto.ToString("N") : null)</td>
                    </tr>
                }
            }
            
        </tbody>
    </table>
}

ManejoPresupuestoApp/Views/Shared/_ResumenTotales.cshtml
@model TransaccionesResumenTotal

@{
    string cadenaClase = (Model.Total >= 0 ? "activo" : "pasivo");
}

<div class="contenedor-totales mb-3">
    <div>
        <div>
            <strong>Depósitos</strong>
        </div>
        <div class="activo">
            @Model.Ingresos.ToString("N")
        </div>
    </div>
    <div>
        <div>
            <strong>Retiros</strong>
        </div>
        <div class="pasivo">
            @Model.Gastos.ToString("N")
        </div>
    </div>
    <div>
        <div>
            <strong>Totales</strong>
        </div>
        <div class="@cadenaClase">
            @Math.Abs(Model.Total).ToString("N")
        </div>
    </div>
</div>