ManejoPresupuestoApp/Controllers/TiposCuentasController.cs
using Dapper;
using ManejoPresupuestoApp.Models;
using ManejoPresupuestoApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Linq;

namespace ManejoPresupuestoApp.Controllers
{
    public class TiposCuentasController : Controller
    {
        private readonly IRepositoriosTiposCuentas _repositoriosTiposCuentas;
        private readonly IServiciosUsuarios _serviciosUsuarios;
        public TiposCuentasController(IRepositoriosTiposCuentas repositoriosTiposCuentas,
                                      IServiciosUsuarios serviciosUsuarios)
        {
            _repositoriosTiposCuentas = repositoriosTiposCuentas;
            _serviciosUsuarios = serviciosUsuarios;
        }

        public async Task<IActionResult> Index()
        { 
            IEnumerable<TipoCuenta> lstCuentas = await _repositoriosTiposCuentas.ListadoTiposCuentas(_serviciosUsuarios.ObtenerUsuarioId());

            return View(lstCuentas);
        }


        public IActionResult Crear()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            var tipoCuenta = await _repositoriosTiposCuentas.ConsultarPorId(id, usuarioId);

            if (tipoCuenta == null)
            {
                return RedirectToAction("NoEncontrado","Home");
            }

            return View(tipoCuenta);
        }

        [HttpPost]
        public async Task<IActionResult> Crear(TipoCuenta tipoCuenta)
        {
            if (!ModelState.IsValid)
            {
                return View(tipoCuenta);
            }

            tipoCuenta.UsuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            if (!await _repositoriosTiposCuentas.Existe(tipoCuenta))
            {
                await _repositoriosTiposCuentas.Crear(tipoCuenta);
            }
            else
            {
                ModelState.AddModelError(nameof(tipoCuenta.Nombre), "Ya existe un tipo de cuenta con este valor");
                return View(tipoCuenta);
            }
           

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Actualizar(TipoCuenta tipoCuenta)
        {
            if (!ModelState.IsValid)
            {
                return View("Editar",tipoCuenta);
            }

            tipoCuenta.UsuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            try
            { 
                int resultado = await _repositoriosTiposCuentas.Actualizar(tipoCuenta);
                if (resultado == 0)
                    throw new Exception("No hay datos a modificar");
            }
            catch (Exception ex)
            {
                //Se añade error al modelo
                ModelState.AddModelError(string.Empty, ex.Message);
                return View("Editar", tipoCuenta);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Borrar(TipoCuenta tipoCuenta)
        {
            tipoCuenta.UsuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            var tipoCuentaConsulta = await _repositoriosTiposCuentas.ConsultarPorId(tipoCuenta.Id, tipoCuenta.UsuarioId);
            if (tipoCuentaConsulta == null)
                return RedirectToAction("NoEncontrado", "Home");

            return View(tipoCuentaConsulta);
        }


        [HttpPost]
        public async Task<IActionResult> BorrarTipoCuenta(TipoCuenta tipoCuenta)
        {
            tipoCuenta.UsuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            try
            {
                int resultado = await _repositoriosTiposCuentas.Borrar(tipoCuenta);
                if (resultado == 0)
                    throw new Exception("No hay datos a borrar");
            }
            catch (Exception ex)
            {
                //Se añade error al modelo
                ModelState.AddModelError(string.Empty, ex.Message);
                return View("Index");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> ExisteTipoCuenta(string nombre)
        {
            var yaExiste = await _repositoriosTiposCuentas.Existe(new TipoCuenta { UsuarioId = _serviciosUsuarios.ObtenerUsuarioId(), Nombre = nombre });

            return (yaExiste ? Json($"El nombre ya existe") : Json(true));
        }

        [HttpPost]
        public async Task<IActionResult> Sort([FromBody] int[] ids)
        {
            var UsuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            List<TipoCuenta> tiposCuentasOrdenados;

            //Selecciona los ids del listado
            var tiposCuentas = await _repositoriosTiposCuentas.ListadoTiposCuentas(UsuarioId);
            var idsTiposCuentas = tiposCuentas.Select(x => x.Id);

            //Toma los ids que llega por parámetro y los compara con los que devuelve el listado
            var idsNoSonUsuario = ids.Except(idsTiposCuentas).ToList();
            if (idsNoSonUsuario.Count > 0)
                return Forbid();
            else
            {
                tiposCuentasOrdenados = ids.Select((valor, indice) => new TipoCuenta() {
                    Id = valor,
                    UsuarioId = UsuarioId,
                    Orden = indice + 1
                }).ToList();
            }

            await _repositoriosTiposCuentas.Sort(tiposCuentasOrdenados);

            return Ok();
        }
    }

}

ManejoPresupuestoApp/Views/TiposCuentas/Borrar.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Borrar Tipos de cuenta";
}

<h3 class="mb-3">¿Estás seguro que desea borrar la cuenta @Model.Nombre?</h3>
<form asp-controller="TiposCuentas" asp-action="BorrarTipoCuenta">
    <input type="hidden" asp-for="Id" />

    <button type="submit" class="btn btn-danger">Borrar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

ManejoPresupuestoApp/Views/TiposCuentas/Crear.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Tipos de cuenta";
}

<h1>Crear Tipo de cuenta</h1>
<h5>Se refiere a cómo vamos a agrupar las cuentas: Préstamos, tarjeta de crédito</h5>

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<form id="form1" asp-controller="TiposCuentas" asp-action="Crear" >
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial"></partial>
}

ManejoPresupuestoApp/Views/TiposCuentas/Editar.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Editar Tipos de cuenta";
}

<h1>Modificar Tipo de cuenta @Model.Nombre</h1>
<h5>Se refiere a cómo vamos a agrupar las cuentas: Préstamos, tarjeta de crédito</h5>

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<form id="form1" asp-controller="TiposCuentas" asp-action="Actualizar" >
    <input type="hidden" asp-for="@Model.Id"/>
    <div class="mb-3">
        <label asp-for="@Model.Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a class="btn btn-secondary" asp-action="Index">Cancelar</a>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial"></partial>
}

ManejoPresupuestoApp/Views/TiposCuentas/Index.cshtml
@using System.ComponentModel.DataAnnotations;
@using System.ComponentModel;
@model IEnumerable<TipoCuenta>
@{
    ViewData["Title"] = "Tipos Cuentas";
}

<h1>Tipos de cuentas</h1>
<hr />
<h5>Se refiere a cómo vamos a agrupar las cuentas: Préstamos, tarjeta de crédito</h5>

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<table class="table">
    <thead>
        <tr>
        @{
                TipoCuenta tipoCuenta = new TipoCuenta();
                var lstExcepts = tipoCuenta.GetType().GetProperties().Where(x=>x.Name=="Orden");
                foreach (var elem in tipoCuenta.GetType().GetProperties().Except(lstExcepts))
                {
                    var attr = (DisplayNameAttribute) elem.GetCustomAttributes(typeof(DisplayNameAttribute), false).FirstOrDefault();
                    if (attr != null)
                    {
                        <th>@attr.DisplayName</th>
                    }
                    else
                    {
                        <th>@elem.Name</th>
                    }
                }
                <th>Acciones</th>
            }
        </tr>
    </thead>
    <tbody id="reordenable">       
        @foreach (var elemTipoCuenta in Model)
        {
            <tr>
                <input type="hidden" asp-for="@elemTipoCuenta.Id" name="ids"/>
            @foreach (var elem1 in elemTipoCuenta.GetType().GetProperties().Except(lstExcepts)) 
            {
                <td>@elem1.GetValue(elemTipoCuenta)</td>
            }
                <td>
                    <a asp-action="Editar" class="btn btn-primary" asp-route-id="@elemTipoCuenta.Id">Editar</a>
                    <a asp-action="Borrar" class="btn btn-danger" asp-route-id="@elemTipoCuenta.Id">Borrar</a>
                </td>
            </tr>
        }                  
    </tbody>
</table>
<a asp-action="Crear" asp-controller="TiposCuentas" class="btn btn-primary">Crear Nueva Cuenta</a>

@section Scripts{
    <script>
        const urlOrdenar = '@Url.Action("Sort")';
        $(() => {
            $("#reordenable").sortable(
                {
                    //Cuando se acabe de arrastar, ejecuta una función.
                    stop: async function (e, ui){
                        await actualizarOrden();
                    }
                }
            );
        });

        async function actualizarOrden()
        {
            const ids = obtenerIds();
            await enviarIdsBD(ids);
        }

        function obtenerIds()
        {
            //Se recorre todos los elementos, obtiene su valor y lo transforma en un array.
            return $('[name="ids"]').map(function (){return $(this).val()}).get();
        }

        //llamada mediante fetch
        async function enviarIdsBD(ids)
        {
            const response = await fetch(urlOrdenar, {
                method: 'POST', // *GET, POST, PUT, DELETE, etc       
                headers: {
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify(ids) // body data type must match "Content-Type" header
            });
        }
    </script>
}